backend:
  name: git-gateway
  branch: main # ඔයාගේ GitHub branch එක

media_folder: "images" # Thumbnails save වෙන තැන
public_folder: "/images"

collections:
  - name: "videos"
    label: "Videos"
    folder: "content/videos" # පෝස්ට් save වෙන තැන
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Video Embed Link", name: "video_url", widget: "string"}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown"}
